development:
  adapter: postgresql
  encoding: unicode
  database: database_name_development
  pool: 5
  host: localhost
  username: postgres
  password: Icui4cu#

test:
  adapter: postgresql
  encoding: unicode
  database: database_name_test
  pool: 5
  username: postgres
  password: Icui4cu#

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
